version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes_backend
    ports:
      - "5500:5500"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
    networks:
      - notes_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - notes_network

networks:
  notes_network:
    driver: bridge
